export enum AuditCategory {
  AUTH = 'AUTH',
  CRUD = 'CRUD',
  PAYMENT = 'PAYMENT',
}

export enum AuthAuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_LOGOUT_ALL = 'USER_LOGOUT_ALL',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_CONFIRM = 'PASSWORD_RESET_CONFIRM',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
}

export enum CrudAuditAction {
  RESOURCE_CREATED = 'RESOURCE_CREATED',
  RESOURCE_UPDATED = 'RESOURCE_UPDATED',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  RESOURCE_SOFT_DELETED = 'RESOURCE_SOFT_DELETED',
  RESOURCE_RESTORED = 'RESOURCE_RESTORED',
}

export enum PaymentAuditAction {
  PAYMENT_INTENT_CREATED = 'PAYMENT_INTENT_CREATED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
  PAYMENT_CANCELLED = 'PAYMENT_CANCELLED',
}

export enum AuditResourceType {
  ROLE = 'ROLE',
  USER = 'USER',
  TOUR = 'TOUR',
  HOTEL = 'HOTEL',
  ROOM = 'ROOM',
  BOOKING = 'BOOKING',
  TOUR_BOOKING = 'TOUR_BOOKING',
  REVIEW = 'REVIEW',
  TOUR_GUIDE = 'TOUR_GUIDE',
  PAYMENT = 'PAYMENT',
  AUTH_SESSION = 'AUTH_SESSION',
}

export type AuditAction =
  | AuthAuditAction
  | CrudAuditAction
  | PaymentAuditAction;
