export const NOTIFICATION_QUEUE = 'notification';

export enum NotificationEvent {
  GUIDE_REGISTERED = 'guide.registered',
  GUIDE_VERIFIED = 'guide.verified',
  TOUR_CREATED = 'tour.created',
  TOUR_UPDATED = 'tour.updated',
  TOUR_DELETED = 'tour.deleted',
  TOUR_INVENTORY_LOW = 'tour.inventory.low',
  TOUR_INVENTORY_SOLD_OUT = 'tour.inventory.sold_out',
  TOUR_INVENTORY_RESTOCKED = 'tour.inventory.restocked',
  TOUR_BOOKING_CREATED = 'tour.booking.created',
  TOUR_BOOKING_CONFIRMED = 'tour.booking.confirmed',
  TOUR_BOOKING_CANCELLED = 'tour.booking.cancelled',
  TOUR_BOOKING_PAYMENT_FAILED = 'tour.booking.payment_failed',
  TOUR_BOOKING_OVERBOOKING = 'tour.booking.overbooking',
}

export enum NotificationType {
  GUIDE_REGISTRATION_PENDING = 'GUIDE_REGISTRATION_PENDING',
  GUIDE_VERIFIED = 'GUIDE_VERIFIED',
  GUIDE_REJECTED = 'GUIDE_REJECTED',
  TOUR_CREATED = 'TOUR_CREATED',
  TOUR_UPDATED = 'TOUR_UPDATED',
  TOUR_DELETED = 'TOUR_DELETED',
  TOUR_PUBLISHED = 'TOUR_PUBLISHED',
  TOUR_UNPUBLISHED = 'TOUR_UNPUBLISHED',
  TOUR_INVENTORY_LOW = 'TOUR_INVENTORY_LOW',
  TOUR_INVENTORY_SOLD_OUT = 'TOUR_INVENTORY_SOLD_OUT',
  TOUR_INVENTORY_RESTOCKED = 'TOUR_INVENTORY_RESTOCKED',
  TOUR_BOOKING_CREATED = 'TOUR_BOOKING_CREATED',
  TOUR_BOOKING_CONFIRMED = 'TOUR_BOOKING_CONFIRMED',
  TOUR_BOOKING_CANCELLED = 'TOUR_BOOKING_CANCELLED',
  TOUR_BOOKING_PAYMENT_FAILED = 'TOUR_BOOKING_PAYMENT_FAILED',
  TOUR_BOOKING_OVERBOOKING = 'TOUR_BOOKING_OVERBOOKING',
}
